create table(
id NUMBER GENERATED ALWAYS AS IDENTITY
description VARCHAR2(40) NOT NULL
--description VARCHAR2(4000)
--
rowversion INTEGER NOT NULL
created TIMESTAMP WITH LOCAL TIME ZONE NOT NULL
created_by VARCHAR2(30) NOT NULL
updated TIMESTAMP WITH LOCAL TIME ZONE NOT NULL
updated_by VARCHAR2(30) NOT NULL
);
