create user APPMAN identified by password;

GRANT CREATE DIMENSION TO APPMAN;
GRANT CREATE TABLE TO APPMAN;
GRANT CREATE JOB TO APPMAN;
GRANT CREATE TYPE TO APPMAN;
GRANT CREATE VIEW TO APPMAN;
GRANT CREATE INDEXTYPE TO APPMAN;
GRANT CREATE CLUSTER TO APPMAN;
GRANT CREATE PROCEDURE TO APPMAN;
GRANT UNLIMITED TABLESPACE TO APPMAN;
GRANT CREATE SESSION TO APPMAN;
GRANT CREATE MATERIALIZED VIEW TO APPMAN;
GRANT CREATE SEQUENCE TO APPMAN;
GRANT CREATE TRIGGER TO APPMAN;
GRANT CREATE SYNONYM TO APPMAN;
