create user DEMO identified by password;

GRANT CREATE DIMENSION TO DEMO;
GRANT CREATE TABLE TO DEMO;
GRANT CREATE JOB TO DEMO;
GRANT CREATE TYPE TO DEMO;
GRANT CREATE VIEW TO DEMO;
GRANT CREATE INDEXTYPE TO DEMO;
GRANT CREATE CLUSTER TO DEMO;
GRANT CREATE PROCEDURE TO DEMO;
GRANT UNLIMITED TABLESPACE TO DEMO;
GRANT CREATE SESSION TO DEMO;
GRANT CREATE MATERIALIZED VIEW TO DEMO;
GRANT CREATE SEQUENCE TO DEMO;
GRANT CREATE TRIGGER TO DEMO;
GRANT CREATE SYNONYM TO DEMO;
